# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "xebia-devops" do |web|
	  web.vm.box = "xebia-devops-centosv64-x64"
	  web.vm.hostname = "xebia-devops"
	  
	  web.ssh.username = "vagrant"
	  web.ssh.private_key_path = "../ssh/xebia.id.rsa"
	
	  #shared folder for accessing yum repository
	  web.vm.synced_folder "~/tools/xebia/shared-data/yum", "/yum"
	  
	  #setting port forward for tomcat
	  web.vm.network :forwarded_port, guest: 8080, host: 8090
	  
	  web.vm.provider :virtualbox do |vbox|
	    vbox.name = "xebia-devops"
	  end
	 
	  web.vm.provision :puppet do |puppet|
	    puppet.options = "--verbose --debug"
	    puppet.manifests_path = "puppet/manifests"
	    puppet.manifest_file = "site.pp"
	  end
  end
end
